/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "#111317",
        surface: "#111317",
        "surface-dim": "#111317",
        "surface-bright": "#37393d",
        "surface-container-lowest": "#0c0e12",
        "surface-container-low": "#1a1c1f",
        "surface-container": "#1e2023",
        "surface-container-high": "#282a2e",
        "surface-container-highest": "#333539",
        "on-surface": "#e2e2e7",
        "on-surface-variant": "#e4bfb1",
        "inverse-surface": "#e2e2e7",
        "inverse-on-surface": "#2e3034",
        outline: "#ab8a7d",
        "outline-variant": "#5b4137",
        "surface-tint": "#ffb599",
        primary: "#ffb599",
        "on-primary": "#5a1c00",
        "primary-container": "#ff5f00",
        "on-primary-container": "#531a00",
        "inverse-primary": "#a63b00",
        secondary: "#c5c5d1",
        "on-secondary": "#2e3039",
        "secondary-container": "#454650",
        "on-secondary-container": "#b4b4c0",
        tertiary: "#c2c5de",
        "on-tertiary": "#2b2f43",
        "tertiary-container": "#8f92aa",
        "on-tertiary-container": "#272b3f",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#ffdbce",
        "primary-fixed-dim": "#ffb599",
        "on-primary-fixed": "#370e00",
        "on-primary-fixed-variant": "#7f2b00",
        "secondary-fixed": "#e2e1ee",
        "secondary-fixed-dim": "#c5c5d1",
        "on-secondary-fixed": "#191b24",
        "on-secondary-fixed-variant": "#454650",
        "tertiary-fixed": "#dee1fb",
        "tertiary-fixed-dim": "#c2c5de",
        "on-tertiary-fixed": "#161b2d",
        "on-tertiary-fixed-variant": "#42465a",
        "on-background": "#e2e2e7",
        "surface-variant": "#333539",
      },
      fontFamily: {
        headline: ["Sora", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Space Grotesk", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg": ["40px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "700" }],
        interactive: ["14px", { lineHeight: "1", fontWeight: "600" }],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "24px",
        "margin-desktop": "48px",
        "margin-mobile": "16px",
        "container-max": "1280px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
    },
  },
  plugins: [],
};
